### ISSUE TITLE
[Bug report] npm i error and some question for electron

### ISSUE THREAD

**Issue by RSS1102** [webdriverio/electron-boilerplate#45]
node version: `v20.10.0` or `v18.19.0`

1.  I don't know how many node versions this project should use.I tried two node versions to execute `npm i` but failed.
```cmd
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'D:\\GitHub\\electron-boilerplate\\node_modules\\bplist-creator',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\GitHub\electron-boilerplate\node_modules\bplist-creator\node_modules\stream-buffers\coverage\lcov-report'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'D:\\GitHub\\electron-boilerplate\\node_modules\\bplist-creator\\node_modules\\stream-buffers\\coverage\\lcov-report'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
```
---
2.  I am currently using an `electron builder` ,is it the same testing method? (Configuration files and dependencies)[electron-vite-react](https://github.com/electron-vite/electron-vite-react).

---

3. I see that the location of this configuration file is different from the file generated using`npm create wdio@latest ./` . How should I consider and determine the location and some config for different ?
![image](https://github.com/webdriverio/electron-boilerplate/assets/81673017/f4c479f8-8184-400f-99a3-bd836bd7eb53)
![image](https://github.com/webdriverio/electron-boilerplate/assets/81673017/e603588c-867a-4304-9fea-bf1a49869f30)

**Comment by RSS1102** [comment]
even if  `Now using node v20.8.0 (64-bit)`

**Comment by christian-bromann** [comment]
> 1. I don't know how many node versions this project should use.I tried two node versions to execute `npm i` but failed.

This doesn't seem like a WebdriverIO related bug and more connected with wrong set permissions on Windows.

> 3\. I am currently using an `electron builder` ,is it the same testing method? (Configuration files and dependencies)[electron-vite-react](https://github.com/electron-vite/electron-vite-react).

I recommend using https://webdriver.io/docs/wdio-electron-service

> 3\. How should I consider and determine the location and some config for different ?

This is up to you where you put the config files. WebdriverIO only makes a suggestion here.

Please join our [Discord](https://discord.webdriver.io) Server if you have further questions. We have a channel for "Desktop Testing" were more people can help you out.

Cheers!

**Comment by RSS1102** [comment]
ok,Thank you for your explanation.
